server:
  port: 8082

spring:
  application:
    name: common-service

  datasource:
    url: jdbc:postgresql://localhost:5432/test
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1998177

logging:
  level:
    com.example.interceptor: DEBUG

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true