server:
  port: 8086

spring:
  application:
    name: mail-service

  datasource:
    url: jdbc:postgresql://localhost:5432/test
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1998177

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
   host: smtp.gmail.com
   port: 587
   username: kirillbrigi177@gmail.com
   password: seow pqdn hing sfrc
   properties:
    mail:
      smtp:
        auth: true
        starttls:
         enable: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: email-service-group2
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer