server:
  port: 8080

spring:
  application:
   name: user-service

  datasource:
    url: jdbc:postgresql://localhost:5432/test
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1998177

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: kirillbrigi177@gmail.com
    password: tegm whsb nvbk ydbr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
