server:
  port: 8082

spring:
  application:
    name: scheduler-service
  datasource:
    url: jdbc:postgresql://localhost:5432/scheduler
    username: postgres
    password: 1998177
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true




